name: Omini CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

runs-on: ubuntu-latest

jobs:
  ci:
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

  cd:
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Release
        uses: ./.github/actions/release
