name: Omini CI/CD - PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: build
        name: Build
        uses: ./.github/actions/build
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}

  cd:
    needs: ci
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://omini.danilokasparian.com.br

    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: ./.github/actions/release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
          AWS_INVALIDATION_DISTRIBUTION_ID: ${{ vars.AWS_INVALIDATION_DISTRIBUTION_ID }}
        with:
          artifact-name: ${{ needs.ci.outputs.artifact-name }}
